=== hmrc/interest-restriction-return/public/api/conf/1.0/schemas/appointReportingCompanySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Provides the ability to appoint a reporting company for the group",
  "type": "object",
  "properties": {
    "agentDetails": {
      "description": "Details of the agent where an agent is submitting on behalf of the reporting company",
      "$ref": "subSchemas/agentDetails.json"
    },
    "reportingCompany": {
      "$ref": "subSchemas/reportingCompany.json"
    },
    "authorisingCompanies": {
      "description": "Details of companies authorising the appointment",
      "$ref": "subSchemas/authorisingCompanies.json"
    },
    "isReportingCompanyAppointingItself": {
      "description": "Indicate whether the reporting company is appointing itself",
      "type": "boolean"
    },
    "identityOfAppointingCompany": {
      "description": "Details of the company appointing the reporting company",
      "$ref": "subSchemas/identityOfCompanySubmitting.json"
    },
    "ultimateParentCompany": {
      "$ref": "subSchemas/ultimateParent.json"
    },
    "accountingPeriod" : {
      "description": "The worldwide group's period of account",
      "$ref": "subSchemas/accountingPeriod.json"
    },
    "declaration": {
      "description": "Statement to confirm the truth of the information given and that the authorising companies listed make up at least 50% of eligible companies in the group",
      "$ref": "definitions/definitions.json#/definitions/declaration"
    }
  },
  "required": [
    "agentDetails",
    "authorisingCompanies",
    "reportingCompany",
    "isReportingCompanyAppointingItself",
    "accountingPeriod",
    "declaration"
  ],
  "additionalProperties": false
}

=== hmrc/interest-restriction-return/public/api/conf/1.0/examples/reportingCompany/appoint/request.json
{
  "agentDetails": {
    "agentActingOnBehalfOfCompany": true,
    "agentName": "AAgent"
  },
  "reportingCompany": {
    "companyName": "ACompany",
    "ctutr": "1123456789",

    "sameAsUltimateParent": true
  },
  "isReportingCompanyAppointingItself":false,
  "identityOfAppointingCompany": {
    "companyName": "BCompany",
    "ctutr": "9999999999"
  },
  "authorisingCompanies": [{
    "companyName": "CCompany",
    "ctutr": "5555555555"
  }],
  "accountingPeriod": {
    "startDate": "2018-11-01",
    "endDate": "2019-12-01"
  },
  "declaration": true
}
